### ISSUE TITLE
Add widgets to make the documentation concise

### ISSUE THREAD

**Issue by mehdie79** [FormulaCarbon/pythings-Python-Module#1]
Here is the fork link: https://github.com/mehdie79/pythings-Python-Module

I have restyled the README.md document by adding widget-like functionality to all the command boxes. This will make the documentation concise and easier to navigate (i.e. users have to less scroll up/down). Hope this helps!

**Comment by FormulaCarbon** [comment]
Thanks! I am too involved in other projects and schoolwork. I also don’t have the resources to test this module properly. If you would like, I will add you as a contributor and you can take over this project.

**Comment by mehdie79** [comment]
Hi! Thank you for your notes. Yes, I would like to be added as a contributor.

**Comment by FormulaCarbon** [comment]
I sent the invite!
